server:
  port: 8095
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  profiles:
    active: dev
springdoc:
  paths-to-match: /v1/**, /api/**
  packages-to-scan: com.personal.chronikale.controller
project:
  image: images/
  
logging:
  level:
    org.springframework: info
    
  
        

  main:
    web-application-type: servlet
       
